#include <stdio.h>
#include <math.h>
#include <string.h>

#define N 512
#define N_half 512/2
#define TWO_PI 6.28318530718

float ReX[ (N / 2)  ];
float ImX[ (N / 2)  ];

float PI = 3.14159265;
double input[N-1];
float remap_output_end = 0.0;

/*
	This function reads input arguments from a text file
	Generates a sine wave based on those arguments
	Stores the sine wave in another text file
*/
void sin_gen()
{
	// Base values
	int Fsample = 1000;
	int Fsignal = 100;
	int amp = 0;
	int phase = 0;
	int dc = 0;
	int i = 0;

	memset(input, 0, sizeof(input));
	
	char line[256]; // Used to store each line in the text file
	int init_size = strlen(line);
	char delim[] = ","; // The delimiting character
	
	FILE *fp;
	
	fp = fopen("settings.txt", "r");
	
	fgets(line, sizeof(line), fp);
	printf("%s\n", line);
	
	char *ptr = strtok(line, delim); // Find the first argument
	
	// Loop through the line and parse the arguments
	while(ptr != NULL)
	{
		switch(i)
		{
			case 0:
			{
				amp = atoi(ptr);
			}break;
			case 1:
			{
				Fsample = atoi(ptr);
			}break;
			case 2:
			{
				Fsignal = atoi(ptr);
			}break;
			case 3:
			{
				phase = atoi(ptr);
			}break;
			case 4:
			{
				dc = atoi(ptr);
			}break;
			default:
			{
				printf("Hello\n");
			}break;
			
		}
		
//		printf("%d\t", atoi(ptr)); 	// Debug
//		printf("'%s'\n", ptr); 		// Debug
		ptr = strtok(NULL, delim); 	// find the next argument
		i++;
	}
	 
	// Debug
//	printf("Amp = %d\n", amp);
//	printf("Fsample = %d\n", Fsample);
//	printf("Fsignal = %d\n", Fsignal);
//	printf("Phase = %d\n", phase);
//	printf("DC = %d\n", dc);
	
	fclose(fp);
	
	remap_output_end = (float)Fsample; // Store so DFT() can remap the x-axis
	
	fp = fopen("sine.txt", "w+");
	
	// Generate sine values
	float j;
	for(j = 0, i = 0; j < N; j++, i++)
	{
		input[i] = sin(TWO_PI * Fsignal * (j/Fsample));
		fprintf(fp, "%f\n", input[i]);
	}
	
	fclose(fp);
}

/*
	This function performs a Discrete Fourier Analysis
	It uses the sine values generated by sin_gen()
	The output is stored in a text file
	The highest frequency is detected and its value is stored in another text file
*/
void DFT()
{
	FILE *fp;
	fp = fopen("dft_out.txt", "w+");
	int k, i = 0;
	
	for(i = 0; i < N/2; i++)
	{
		ReX[i] = 0;
		ImX[i] = 0;
	}
	
//	printf("i = %d\n\n", i);
//	printf("length: %d\n", (sizeof(ReX)/sizeof(ReX[0])));
	
	// Perform the DFT
	for(k = 0; k < N/2; k++)
	{
		for(i = 0; i < N-1; i++)
		{
			ReX[k] = ReX[k] + input[i]*cos(2*PI*k*i/N);
			ImX[k] = ImX[k] - input[i]*sin(2*PI*k*i/N);
		}
	}
//	printf("i = %d\n\n", --i);
//	printf("i = %d\n\n", --k);
	
	fprintf(fp, "Re\tIm\n");
	for(i = 0; i < N/2+1; i++)
	{
		fprintf(fp, "%f\t%f\n", ReX[i], ImX[i]);
	}
	
	fclose(fp);		
	
	fp = fopen("FSB_IN.txt", "w+");	
	float big_freq = 0.0; 	// Used to store the magnitude of the frequencies
	int loc = 0; 			// Stores the largest frequency 
	float abs = 0.0; 		// Stores the magnitude value of the DFT for a given frequency
	
	// Find the maximal frequency
	for(i = 0; i < N/2; i++) 	// Loop through the DFT values
	{
		abs = sqrt(ReX[i]*ReX[i] + ImX[i]*ImX[i]); // Calculate the magnitude at the given point

		if(big_freq < abs) 		// If the magnitude is greater than any of the previous points
		{
			big_freq = abs; 	// Remember for next round
			loc = remap(i); 	// Store the corresponding frequency
		}
	}
	fprintf(fp, "%d\n", loc); 	// Store the largest frequency
	fclose(fp);	
}	

/*
	This function is used to convert one range of numbers to another range of numbers
	Source: https://stackoverflow.com/questions/5731863/mapping-a-numeric-range-onto-another
*/
int remap(int i)
{
  float input_start = 0.0;
  float input_end = N;
  float output_start = 0.0;
  float output_end = remap_output_end;
  float slope = 0.0;
  
  int output = 0;
  
  slope = (output_end - output_start) / (input_end - input_start);
  output = (int)(output_start + slope * (i -input_start));
  
  return output;
}
	
int main()
{
	sin_gen(); 	// Generate the sine values
	DFT();		// Perform a DFT on the sine values
	
	return 0;
}
